name: tests

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Audit formula
        run: brew audit --strict --online ./Formula/jetbrains-toolbox.rb
      - name: Install + test
        run: |
          brew install ./Formula/jetbrains-toolbox.rb
          brew test jetbrains-toolbox
